# Generated by Django 5.0.1 on 2025-02-27 06:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('childApp', '0001_initial'),
        ('mentorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('deadline', models.DateField(db_index=True, help_text='Specify the deadline for the task', verbose_name='Deadline')),
                ('completed', models.BooleanField(default=False, help_text='Mark as completed', verbose_name='Completed')),
                ('description', models.TextField(help_text='Enter the task details', verbose_name='Task Description')),
                ('additional_details', models.TextField(blank=True, help_text='Enter any additional details about the task', null=True, verbose_name='Additional Details')),
                ('points', models.IntegerField(help_text='Enter the points for the task', verbose_name='Points')),
                ('img', models.ImageField(blank=True, default='defaults/no-image.png', null=True, upload_to='media/images/', verbose_name='Image')),
                ('total_bonus_points', models.IntegerField(default=0, help_text='Total bonus points assigned to this task', verbose_name='Total Bonus Points')),
                ('completed_date', models.DateTimeField(blank=True, help_text='The date when the task was completed', null=True, verbose_name='Completed Date')),
                ('admin_max_points', models.IntegerField(default=0, help_text='Max bonus points assigned to this task', verbose_name='Max Bonus Points')),
                ('checkin_checkout_type', models.BooleanField(blank=True, default=False, help_text='Checkin Checkout Type', null=True, verbose_name='Checkin Checkout Type')),
                ('assigned_children', models.ManyToManyField(blank=True, related_name='assigned_tasks', to='childApp.child', verbose_name='Assigned Children')),
                ('assigned_mentors', models.ManyToManyField(blank=True, related_name='assigned_tasks', to='mentorApp.mentor', verbose_name='Assigned Mentors')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True, help_text='Indicates if the task is new for the child.', verbose_name='Is New')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='childApp.child')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teenApp.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bonus_points', models.IntegerField(default=0)),
                ('remaining_coins', models.IntegerField(default=0, help_text='Unredeemed TeenCoins from this task.')),
                ('checkin_img', models.ImageField(blank=True, null=True, upload_to='checkin_images/', verbose_name='Check-In Image')),
                ('checkout_img', models.ImageField(blank=True, null=True, upload_to='checkout_images/', verbose_name='Check-Out Image')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('mentor_feedback', models.TextField(blank=True, null=True, verbose_name='Mentor Feedback')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childApp.child')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teenApp.task')),
            ],
            options={
                'unique_together': {('child', 'task')},
            },
        ),
    ]
