# Generated by Django 5.0.1 on 2024-08-18 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('identifier', models.CharField(max_length=5, unique=True, verbose_name='Identifier')),
                ('secret_code', models.CharField(max_length=3, verbose_name='Secret Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mentors', models.ManyToManyField(blank=True, related_name='children', to='teenApp.mentor', verbose_name='Mentors')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_points', models.IntegerField(default=1000, verbose_name='Max Points')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter the reward details', verbose_name='Reward Description')),
                ('points_required', models.IntegerField(help_text='Enter the points required for this reward', verbose_name='Points Required')),
                ('img', models.ImageField(blank=True, default='defaults/no-image.png', null=True, upload_to='media/images/', verbose_name='Image')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='teenApp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField(verbose_name='Points Used')),
                ('date_redeemed', models.DateTimeField(auto_now_add=True, verbose_name='Date Redeemed')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teenApp.child', verbose_name='Child')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teenApp.shop', verbose_name='Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Enter the task details', verbose_name='Task Description')),
                ('deadline', models.DateField(db_index=True, help_text='Specify the deadline for the task', verbose_name='Deadline')),
                ('completed', models.BooleanField(default=False, help_text='Mark as completed', verbose_name='Completed')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('img', models.ImageField(blank=True, default='defaults/no-image.png', null=True, upload_to='media/images/', verbose_name='Image')),
                ('points', models.IntegerField(help_text='Enter the points for the task', verbose_name='Points')),
                ('additional_details', models.TextField(blank=True, help_text='Enter any additional details about the task', null=True, verbose_name='Additional Details')),
                ('new_task', models.BooleanField(default=True, help_text='Indicates if the task is new for the child', verbose_name='New Task')),
                ('viewed', models.BooleanField(default=False, help_text='Indicates if the child has viewed the task', verbose_name='Viewed')),
                ('total_bonus_points', models.IntegerField(default=0, help_text='Total bonus points assigned to this task', verbose_name='Total Bonus Points')),
                ('completed_date', models.DateTimeField(blank=True, help_text='The date when the task was completed', null=True, verbose_name='Completed Date')),
                ('admin_max_points', models.IntegerField(default=0, help_text='Max bonus points assigned to this task', verbose_name='Max Bonus Points')),
                ('duration', models.TextField(help_text='Enter the duration of the task', verbose_name='Duration')),
                ('assigned_children', models.ManyToManyField(related_name='assigned_tasks', to='teenApp.child', verbose_name='Assigned Children')),
                ('assigned_mentors', models.ManyToManyField(blank=True, related_name='assigned_tasks', to='teenApp.mentor', verbose_name='Assigned Mentors')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='completed_by_children', to='teenApp.task', verbose_name='Completed Tasks'),
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teenApp.child')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teenApp.task')),
            ],
            options={
                'unique_together': {('child', 'task')},
            },
        ),
    ]
