# Generated by Django 5.0.1 on 2025-01-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checkin_img',
            field=models.ImageField(blank=True, null=True, upload_to='checkin_images/', verbose_name='Check-In Image'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkout_img',
            field=models.ImageField(blank=True, null=True, upload_to='checkout_images/', verbose_name='Check-Out Image'),
        ),
    ]
