# Generated by Django 5.0.1 on 2025-03-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
