# Generated by Django 5.0.1 on 2024-08-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_children',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='teenApp.child', verbose_name='Assigned Children'),
        ),
    ]
