# Generated by Django 5.0.1 on 2024-05-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reward',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='tasks_completed', to='teenApp.child', verbose_name='Completed By'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(default=0, help_text='Unique Task ID', unique=True, verbose_name='Task ID'),
        ),
        migrations.AlterField(
            model_name='child',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='children_completed', to='teenApp.task', verbose_name='Completed Tasks'),
        ),
    ]
