# Generated by Django 5.0.1 on 2024-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='identifier',
            field=models.CharField(max_length=5, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='child',
            name='secret_code',
            field=models.CharField(max_length=3, verbose_name='Secret Code'),
        ),
    ]
