# Generated by Django 5.0.1 on 2025-01-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0002_task_checkin_img_task_checkout_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='checkin_img',
        ),
        migrations.RemoveField(
            model_name='task',
            name='checkout_img',
        ),
    ]
