# Generated by Django 5.0.1 on 2024-05-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0002_alter_child_identifier_alter_child_secret_code'),
        ('teenApp', '0002_remove_task_reward_task_completed_by_task_task_id_and_more'),
    ]

    operations = [
    ]
