# Generated by Django 5.0.1 on 2024-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0002_alter_task_assigned_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='bonus_points',
            field=models.IntegerField(default=0),
        ),
    ]
