# Generated by Django 5.0.1 on 2024-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0003_taskcompletion_bonus_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
