# Generated by Django 5.0.1 on 2024-04-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0003_task_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Image'),
        ),
    ]
