# Generated by Django 5.0.1 on 2024-05-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0003_merge_20240512_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='completed_tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_by',
        ),
        migrations.AddField(
            model_name='child',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='tasks_completed', to='teenApp.child', verbose_name='Completed By'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='children_completed_tasks', to='teenApp.task', verbose_name='Completed Tasks'),
        ),
    ]
