# Generated by Django 5.0.1 on 2025-03-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0003_taskassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='admin_max_points',
        ),
        migrations.RemoveField(
            model_name='task',
            name='checkin_checkout_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='total_bonus_points',
        ),
    ]
