# Generated by Django 5.0.1 on 2024-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0004_remove_child_completed_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_tasks',
        ),
        migrations.AddField(
            model_name='child',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='completed_by_children', to='teenApp.task', verbose_name='Completed Tasks'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='tasks_completed', to='teenApp.child', verbose_name='Completed By'),
        ),
    ]
