# Generated by Django 5.0.1 on 2024-04-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0004_alter_task_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=10, help_text='Enter the points for the task', verbose_name='Points'),
            preserve_default=False,
        ),
    ]
