# Generated by Django 5.0.1 on 2025-03-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0004_remove_task_admin_max_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Mark as a template for future duplication', verbose_name='Template'),
        ),
    ]
