# Generated by Django 5.0.1 on 2025-01-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0004_task_checkin_img_task_checkout_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='checkin_img',
        ),
        migrations.RemoveField(
            model_name='task',
            name='checkout_img',
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='checkin_img',
            field=models.ImageField(blank=True, null=True, upload_to='checkin_images/', verbose_name='Check-In Image'),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='checkout_img',
            field=models.ImageField(blank=True, null=True, upload_to='checkout_images/', verbose_name='Check-Out Image'),
        ),
    ]
