# Generated by Django 5.0.1 on 2024-04-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0005_task_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.CharField(blank=True, help_text='Enter the reward for this task', max_length=200, verbose_name='Reward'),
        ),
    ]
