# Generated by Django 5.0.1 on 2025-01-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0005_remove_task_checkin_img_remove_task_checkout_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='mentor_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Mentor Feedback'),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
