# Generated by Django 5.0.1 on 2024-05-14 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0005_remove_child_completed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='teenApp.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='max_points',
            field=models.IntegerField(default=1000, verbose_name='Max Points'),
        ),
    ]
