# Generated by Django 5.0.1 on 2025-03-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0005_task_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
