# Generated by Django 5.0.1 on 2024-04-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0006_task_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter the reward details', verbose_name='Reward Description')),
                ('points_required', models.IntegerField(help_text='Enter the points required for this reward', verbose_name='Points Required')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.ForeignKey(blank=True, help_text='Select reward for this task', null=True, on_delete=django.db.models.deletion.CASCADE, to='teenApp.reward', verbose_name='Reward'),
        ),
    ]
