# Generated by Django 5.0.1 on 2025-04-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0006_taskassignment_refunded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin this task to highlight it for mentors and children', verbose_name='Pinned'),
        ),
    ]
