# Generated by Django 5.0.1 on 2025-01-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0006_taskcompletion_mentor_feedback_taskcompletion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='viewed',
        ),
    ]
