# Generated by Django 5.0.1 on 2025-01-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0006_medal_criterion_medal_points_reward'),
        ('teenApp', '0007_remove_task_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='new_task',
        ),
        migrations.AddField(
            model_name='task',
            name='new_for_children',
            field=models.ManyToManyField(blank=True, related_name='new_tasks', to='childApp.child', verbose_name='New For Children'),
        ),
    ]
