# Generated by Django 5.0.1 on 2025-04-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0008_campaign'),
        ('teenApp', '0007_task_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='shopApp.campaign'),
        ),
        migrations.AddField(
            model_name='task',
            name='proof_required',
            field=models.BooleanField(default=True),
        ),
    ]
