# Generated by Django 5.0.1 on 2024-04-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0007_reward_alter_task_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reward',
        ),
    ]
