# Generated by Django 5.0.1 on 2024-04-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0008_remove_task_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.ForeignKey(blank=True, help_text='Select reward for this task', null=True, on_delete=django.db.models.deletion.CASCADE, to='teenApp.reward', verbose_name='Reward'),
        ),
    ]
