# Generated by Django 5.0.1 on 2024-05-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0008_alter_reward_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, default='images/logo.png', null=True, upload_to='media/images/', verbose_name='Image'),
        ),
    ]
