# Generated by Django 5.0.1 on 2025-02-01 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0006_medal_criterion_medal_points_reward'),
        ('teenApp', '0008_remove_task_new_task_task_new_for_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='new_for_children',
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True, help_text='Indicates if the task is new for the child.', verbose_name='Is New')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='childApp.child')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teenApp.task')),
            ],
        ),
    ]
