# Generated by Django 5.0.1 on 2024-04-04 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0009_task_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reward',
        ),
        migrations.AddField(
            model_name='reward',
            name='tasks',
            field=models.ForeignKey(blank=True, help_text='Select tasks for this reward', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='teenApp.task', verbose_name='Tasks'),
        ),
    ]
