# Generated by Django 5.0.1 on 2025-05-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0009_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='send_whatsapp_on_assign',
            field=models.BooleanField(default=True, help_text='If checked, an automatic WhatsApp message will be sent to the user when a task is assigned to them', verbose_name='Send WhatsApp notification when task is assigned'),
        ),
    ]
