# Generated by Django 5.0.1 on 2025-02-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0009_remove_task_new_for_children_taskassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
    ]
