# Generated by Django 5.0.1 on 2025-02-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0009_remove_task_new_for_children_taskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='remaining_coins',
            field=models.IntegerField(default=0, help_text='Unredeemed TeenCoins from this task.'),
        ),
    ]
