# Generated by Django 5.0.1 on 2025-02-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0010_remove_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the task', null=True, verbose_name='Duration'),
        ),
    ]
