# Generated by Django 5.0.1 on 2025-05-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0010_task_send_whatsapp_on_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='checkin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='checkout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TimeWindowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('window_type', models.CharField(choices=[('check_in', 'Check-in'), ('check_out', 'Check-out')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_window_rules', to='teenApp.task')),
            ],
            options={
                'unique_together': {('task', 'specific_date', 'weekday', 'window_type')},
            },
        ),
    ]
