# Generated by Django 5.0.1 on 2025-05-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0011_taskcompletion_checkin_at_taskcompletion_checkout_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='awarded_coins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
