# Generated by Django 5.0.1 on 2024-04-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0011_remove_reward_tasks_task_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Image'),
        ),
    ]
