# Generated by Django 5.0.1 on 2025-02-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0011_task_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
    ]
