# Generated by Django 5.0.1 on 2025-05-28 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0012_taskcompletion_awarded_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='timewindowrule',
            constraint=models.UniqueConstraint(fields=('task', 'window_type'), name='unique_timewindow_per_type_per_task'),
        ),
    ]
