# Generated by Django 5.0.1 on 2024-05-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0012_alter_reward_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='children', to='teenApp.mentor', verbose_name='Mentors'),
        ),
    ]
