# Generated by Django 5.0.1 on 2024-04-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0012_reward_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='additional_details',
            field=models.TextField(blank=True, help_text='Enter any additional details about the task', null=True, verbose_name='Additional Details'),
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.TextField(default=12, help_text='Enter the duration of the task', verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
