# Generated by Django 5.0.1 on 2025-02-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0010_taskcompletion_remaining_coins'),
        ('teenApp', '0012_remove_task_duration'),
    ]

    operations = [
    ]
