# Generated by Django 5.0.1 on 2025-07-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0013_personalinfo_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='proof_requirement',
            field=models.CharField(choices=[('camera', 'העלאת תמונה מהמצלמה בלבד'), ('gallery', 'תמונה מהמצלמה או הגלריה'), ('auto_checkin', 'מאושר אוטומטית אחרי Check-in'), ('auto_checkout', 'מאושר אוטומטית אחרי Check-out')], default='camera', help_text='בחר את סוג ההוכחה הנדרשת מהחניך', max_length=20, verbose_name='דרישת הוכחה'),
        ),
    ]
