# Generated by Django 5.0.1 on 2025-02-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0013_merge_20250213_0042'),
        ('teenApp', '0013_merge_20250214_2009'),
    ]

    operations = [
    ]
