# Generated by Django 5.0.1 on 2024-05-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0013_child_mentors'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_children',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='teenApp.child', verbose_name='Assigned Children'),
        ),
    ]
