# Generated by Django 5.0.1 on 2025-08-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0014_task_proof_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='proof_requirement',
            field=models.CharField(choices=[('camera', 'העלאת תמונה מהמצלמה בלבד'), ('gallery', 'תמונה מהמצלמה או הגלריה'), ('auto_checkin', 'מאושר אוטומטית אחרי Check-in'), ('auto_checkout', 'מאושר אוטומטית אחרי Check-out'), ('none', 'ללא צורך בהעלאת תמונה  ')], default='camera', help_text='בחר את סוג ההוכחה הנדרשת מהחניך', max_length=20, verbose_name='דרישת הוכחה'),
        ),
    ]
