# Generated by Django 5.0.1 on 2025-02-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0014_merge_20250223_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checkin_checkout_type',
            field=models.BooleanField(blank=True, default=False, help_text='Checkin Checkout Type', null=True, verbose_name='Checkin Checkout Type'),
        ),
    ]
