# Generated by Django 5.0.1 on 2024-05-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0014_task_assigned_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_mentors',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='teenApp.mentor', verbose_name='Assigned Mentors'),
        ),
    ]
