# Generated by Django 5.0.1 on 2024-04-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0014_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True, verbose_name='QR Code URL'),
        ),
    ]
