# Generated by Django 5.0.1 on 2025-09-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0015_alter_task_proof_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text="Attach this task to one or more logical groups (e.g., 'for-new-users').", related_name='tasks', to='teenApp.taskgroup'),
        ),
    ]
