# Generated by Django 5.0.1 on 2025-02-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0014_merge_20250222_2324'),
        ('teenApp', '0014_merge_20250225_1318'),
        ('teenApp', '0015_task_checkin_checkout_type'),
    ]

    operations = [
    ]
