# Generated by Django 5.0.1 on 2024-04-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0015_reward_qr_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='qr_code_url',
        ),
    ]
