# Generated by Django 5.0.1 on 2024-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0016_remove_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='new_task',
            field=models.BooleanField(default=True, help_text='Indicates if the task is new for the child', verbose_name='New Task'),
        ),
    ]
