# Generated by Django 5.0.1 on 2024-05-04 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0016_remove_reward_qr_code_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='identifier',
            field=models.CharField(default='00000', max_length=5, unique=True, verbose_name='Identifier'),
        ),
        migrations.AddField(
            model_name='child',
            name='secret_code',
            field=models.CharField(default='000', max_length=3, verbose_name='Secret Code'),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField(verbose_name='Points Used')),
                ('date_redeemed', models.DateTimeField(auto_now_add=True, verbose_name='Date Redeemed')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teenApp.child', verbose_name='Child')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teenApp.reward', verbose_name='Reward')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teenApp.shop', verbose_name='Shop')),
            ],
        ),
    ]
