# Generated by Django 5.0.1 on 2025-10-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0016_taskgroup_task_created_at_task_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('unk', 'Unknown')], default='unk', max_length=10),
        ),
    ]
