# Generated by Django 5.0.1 on 2024-05-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0017_child_identifier_child_secret_code_mentor_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemption',
            name='reward',
        ),
    ]
