# Generated by Django 5.0.1 on 2024-05-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0017_child_identifier_child_secret_code_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='identifier',
            field=models.CharField(max_length=5, unique=True, verbose_name='Identifier'),
        ),
    ]
