# Generated by Django 5.0.1 on 2024-05-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0017_task_new_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='viewed',
            field=models.BooleanField(default=False, help_text='Indicates if the child has viewed the task', verbose_name='Viewed'),
        ),
    ]
