# Generated by Django 5.0.1 on 2025-10-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0018_taskrecurrence_recurringrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='If this task was duplicated from a template, point to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='teenApp.task'),
        ),
    ]
