# Generated by Django 5.0.1 on 2024-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0018_task_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bonus_points',
            field=models.JSONField(blank=True, default=dict, help_text='Bonus points for specific children', null=True),
        ),
    ]
