# Generated by Django 5.0.1 on 2024-05-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0019_task_bonus_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bonus_points',
        ),
    ]
