# Generated by Django 5.0.1 on 2025-10-11 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0019_task_source_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecurrence',
            name='run_time_local',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Time of day to run (Jerusalem local time). Default 08:00.'),
        ),
    ]
