# Generated by Django 5.0.1 on 2024-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0020_remove_task_bonus_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='total_bonus_points',
            field=models.IntegerField(default=0, help_text='Total bonus points assigned to this task', verbose_name='Total Bonus Points'),
        ),
    ]
