# Generated by Django 5.0.1 on 2025-10-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenApp', '0020_alter_taskrecurrence_run_time_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecurrence',
            name='deadline_offset_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional fixed offset (in days) to add to each generated deadline. If not set, the system auto-calculates a non-duplicate date for weekly recurrences.', null=True),
        ),
    ]
