# Generated by Django 5.0.1 on 2025-10-15 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorApp', '0003_mentor_allowed_proof_options'),
        ('teenApp', '0021_taskrecurrence_deadline_offset_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='slug',
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='created_by',
            field=models.ForeignKey(default=0.0007407407407407407, help_text='Mentor who created this group', on_delete=django.db.models.deletion.CASCADE, related_name='task_groups', to='mentorApp.mentor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='taskgroup',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_group_name_per_mentor'),
        ),
    ]
