# Generated by Django 5.0.1 on 2024-12-15 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('childApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_points', models.IntegerField(default=1000, verbose_name='Max Points')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter the reward details', verbose_name='Reward Description')),
                ('points_required', models.IntegerField(help_text='Enter the points required for this reward', verbose_name='Points Required')),
                ('img', models.ImageField(blank=True, default='defaults/no-image.png', null=True, upload_to='media/images/', verbose_name='Image')),
                ('is_visible', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='shopApp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField(verbose_name='Points Used')),
                ('date_redeemed', models.DateTimeField(auto_now_add=True, verbose_name='Date Redeemed')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childApp.child', verbose_name='Child')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.shop', verbose_name='Shop')),
            ],
        ),
    ]
