# Generated by Django 5.0.1 on 2025-02-27 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('childApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_points', models.IntegerField(default=1000, verbose_name='Max Points')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Image')),
                ('city', models.CharField(blank=True, choices=[('TLV', 'תל אביב יפו'), ('TAM', 'טמרה')], max_length=3, null=True, verbose_name='City')),
                ('categories', models.ManyToManyField(related_name='shops', to='shopApp.category', verbose_name='Categories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter the reward details', verbose_name='Reward Description')),
                ('points_required', models.IntegerField(help_text='Enter the points required for this reward', verbose_name='Points Required')),
                ('img', models.ImageField(blank=True, default='defaults/no-image.png', null=True, upload_to='media/images/', verbose_name='Image')),
                ('is_visible', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='shopApp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='RedemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('points_used', models.IntegerField(verbose_name='Total Points Used')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Request Status')),
                ('date_requested', models.DateTimeField(auto_now_add=True, verbose_name='Date Requested')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childApp.child', verbose_name='Child')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.reward', verbose_name='Reward')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.shop', verbose_name='Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField(verbose_name='Points Used')),
                ('date_redeemed', models.DateTimeField(auto_now_add=True, verbose_name='Date Redeemed')),
                ('service_rating', models.IntegerField(blank=True, null=True, verbose_name='Service Rating')),
                ('reward_rating', models.IntegerField(blank=True, null=True, verbose_name='Reward Rating')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childApp.child', verbose_name='Child')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.shop', verbose_name='Shop')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'ראשון'), (1, 'שני'), (2, 'שלישי'), (3, 'רביעי'), (4, 'חמישי'), (5, 'שישי'), (6, 'שבת')], verbose_name='Day of the Week')),
                ('opening_hour', models.TimeField(blank=True, null=True, verbose_name='Opening Hour')),
                ('closing_hour', models.TimeField(blank=True, null=True, verbose_name='Closing Hour')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='shopApp.shop')),
            ],
            options={
                'unique_together': {('shop', 'day')},
            },
        ),
    ]
