# Generated by Django 5.0.1 on 2025-03-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, choices=[('TLV', 'תל אביב יפו'), ('SKN', 'סכנין')], max_length=3, null=True, verbose_name='City'),
        ),
    ]
