# Generated by Django 5.0.1 on 2025-03-02 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_alter_shop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.reward', verbose_name='Reward Used'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Locked At'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='locked_points',
            field=models.IntegerField(default=0, verbose_name='Locked Points'),
        ),
        migrations.AddField(
            model_name='shop',
            name='locked_usage_this_month',
            field=models.IntegerField(default=0, verbose_name='Locked Points This Month'),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10, verbose_name='Request Status'),
        ),
    ]
