# Generated by Django 5.0.1 on 2025-03-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_redemption_reward_redemptionrequest_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
    ]
