# Generated by Django 5.0.1 on 2025-01-24 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_alter_shop_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'ראשון'), (1, 'שני'), (2, 'שלישי'), (3, 'רביעי'), (4, 'חמישי'), (5, 'שישי'), (6, 'שבת')], verbose_name='Day of the Week')),
                ('opening_hour', models.TimeField(blank=True, null=True, verbose_name='Opening Hour')),
                ('closing_hour', models.TimeField(blank=True, null=True, verbose_name='Closing Hour')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='shopApp.shop')),
            ],
            options={
                'unique_together': {('shop', 'day')},
            },
        ),
    ]
