# Generated by Django 5.0.1 on 2025-04-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_redemption_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this shop from children and parents', verbose_name='Is Active'),
        ),
    ]
