# Generated by Django 5.0.1 on 2025-01-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_openinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='reward_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reward Rating'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='service_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Service Rating'),
        ),
    ]
