# Generated by Django 5.0.1 on 2025-04-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_shop_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='openinghours',
            index=models.Index(fields=['shop', 'day'], name='shopApp_ope_shop_id_e2cc8f_idx'),
        ),
    ]
