# Generated by Django 5.0.1 on 2025-01-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_redemption_reward_rating_redemption_service_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
