# Generated by Django 5.0.1 on 2025-01-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_redemption_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(blank=True, choices=[('fast_food', 'אוכל מהיר'), ('cafes', 'בתי קפה'), ('bakeries', 'מאפיות'), ('desserts', 'קינוחים'), ('vegan', 'טבעוני'), ('sushi', 'סושי'), ('pizza', 'פיצה'), ('ice_cream', 'גלידות'), ('health_food', 'מזון בריאות'), ('meat_grill', 'בשרים וגריל'), ('asian', 'אסייתי'), ('italian', 'איטלקי'), ('drinks', 'שתייה'), ('CLOTHES', 'ביגוד'), ('TOYS', 'צעצועים'), ('ELECTRONICS', 'אלקטרוניקה'), ('BOOKS', 'ספרים'), ('OTHER', 'אחר')], max_length=50, null=True, verbose_name='Category'),
        ),
    ]
