# Generated by Django 5.0.1 on 2025-04-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_alter_openinghours_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='day',
            field=models.IntegerField(choices=[(0, 'שני'), (1, 'שלישי'), (2, 'רביעי'), (3, 'חמישי'), (4, 'שישי'), (5, 'שבת'), (6, 'ראשון')], verbose_name='Day of the Week'),
        ),
    ]
