# Generated by Django 5.0.1 on 2025-04-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0007_alter_openinghours_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='campaign_banners/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_children', models.PositiveIntegerField(default=0)),
                ('reward_title', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='shopApp.shop')),
            ],
        ),
    ]
