# Generated by Django 5.0.1 on 2025-04-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0008_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='banner_img',
            field=models.ImageField(blank=True, default='defaults/no-image.png', null=True, upload_to='campaign_banners/'),
        ),
    ]
