# Generated by Django 5.0.1 on 2025-02-21 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0010_merge_20250213_0042'),
        ('shopApp', '0008_category_remove_shop_category_shop_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('points_used', models.IntegerField(verbose_name='Total Points Used')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Request Status')),
                ('date_requested', models.DateTimeField(auto_now_add=True, verbose_name='Date Requested')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childApp.child', verbose_name='Child')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.reward', verbose_name='Reward')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.shop', verbose_name='Shop')),
            ],
        ),
    ]
