# Generated by Django 5.0.1 on 2025-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0011_remove_shop_latitude_remove_shop_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='google_maps_link',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='waze_link',
        ),
        migrations.AddField(
            model_name='shop',
            name='google_map_embed',
            field=models.TextField(blank=True, null=True, verbose_name='Google Maps Embed HTML'),
        ),
    ]
