# Generated by Django 5.0.1 on 2025-09-08 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0012_remove_shop_google_maps_link_remove_shop_waze_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
