# Generated by Django 5.0.1 on 2025-09-08 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0013_shop_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
