AVAILABLE_CITIES = [
    ('TLV', 'תל אביב יפו'),
    ('SKN', 'סכנין'),
]
SHOP_CATEGORIES=[
 ('fast_food', 'אוכל מהיר'),
    ('cafes', 'בתי קפה'),
    ('bakeries', 'מאפיות'),
    ('desserts', 'קינוחים'),
    ('vegan', 'טבעוני'),
    ('sushi', 'סושי'),
    ('pizza', 'פיצה'),
    ('ice_cream', 'גלידות'),
    ('health_food', 'מזון בריאות'),
    ('meat_grill', 'בשרים וגריל'),
    ('asian', 'אסייתי'),
    ('italian', 'איטלקי'),
    ('drinks', 'שתייה'),
    ('CLOTHES', 'ביגוד'),
    ('TOYS', 'צעצועים'),
    ('ELECTRONICS', 'אלקטרוניקה'),
    ('BOOKS', 'ספרים'),
    ('OTHER', 'אחר'),
]


TEEN_COINS_EXPIRATION_MONTHS = 3 # the number of months after which a teen coin expires
MAX_REWARDS_PER_DAY = 1 # the maximum number of rewards per shop that the child can buy in one day
MAX_SHOPS_PER_DAY = 2  # max different shops from which a child can redeem per day
REDEMPTION_REQUEST_EXPIRATION_MINUTES = 60 # the number of minutes after which a redemption request expires
POINTS_PER_LEVEL = 100 # the number of points needed to reach the next level
MAX_PARENT_COINS = 130 # the maximum number of coins a parent can have when the monthly topup is granted
PARENT_TOPUP_AMOUNT = 50 # the amount of coins added to the parent's balance when the monthly topup is granted
CHILDREN_REQUIRE_DEFAULT_IMAGE = {"מחמד_חלילי","الطفل_إبراهيم"}  # the children who have special permissions to upload images in the check in/out page
SPECIAL_UPLOAD_PERMISSIONS_FOR_CHILDREN={"נור_גוראב","أحمد_دنف","آدم_تكروري"}  # the children who have special permissions to upload images in the check in/out page

CAMPAIGN_MENTOR_USERNAME = "אדם_תכרורי" # the username of the campaign mentor
CAMPAIGN_INSTITUTION_NAME = "المحمدية"   # the institution name of the campaign
CAMPAIGN_TIME_LIMIT_MINUTES = 1440 # the time limit for the campaign in minutes
CAMPAIGN_BAN_DURATION_HOURS = 1 # the duration of the campaign ban in hours

LEVELS = {
    1: "מתחיל",
    2: "עוזר",
    3: "שואף",
    4: "שגריר",
    5: "מגן",
    6: "לוחם",
    7: "נועז",
    8: "אור",
    9: "חולם",
    10: "אלוף",
    11: "כוכב",
    12: "חזק",
    13: "נדיב",
    14: "רוח",
    15: "נסיך",
    16: "מאיר",
    17: "תותח",
    18: "מנהיג",
    19: "שולט",
    20: "אגדי",
    21: "שליט",
    22: "שר",
    23: "נאמן",
    24: "מוביל",
    25: "תורם",
    26: "אביר",
    27: "כוח",
    28: "זריז",
    29: "גדול",
    30: "עמיד",
    31: "חכם",
    32: "לבבי",
    33: "מהיר",
    34: "חסד",
    35: "ענק",
    36: "נחוש",
    37: "עוצמתי",
    38: "זוהר",
    39: "נסיך",
    40: "עליון",
    41: "שומר",
    42: "מקסים",
    43: "חולם",
    44: "משפיע",
    45: "שר",
    46: "איתן",
    47: "שליח",
    48: "מעורר",
    49: "מדהים",
    50: "פלאי",
    51: "מורה",
    52: "שר",
    53: "מאסטר",
    54: "עוזר",
    55: "תומך",
    56: "לב",
    57: "מתמיד",
    58: "אלוף",
    59: "שמש",
    60: "מאיר",
    61: "רעם",
    62: "חזון",
    63: "אש",
    64: "גל",
    65: "ברק",
    66: "חלוץ",
    67: "מושלם",
    68: "חבר",
    69: "ספיר",
    70: "נוצה",
    71: "מלאך",
    72: "שקט",
    73: "נס",
    74: "יוצר",
    75: "להב",
    76: "לב",
    77: "אחדות",
    78: "חמלה",
    79: "חלום",
    80: "תקווה",
    81: "אשד",
    82: "שלווה",
    83: "תדר",
    84: "שמחה",
    85: "פרץ",
    86: "פלא",
    87: "אלוף",
    88: "נסיך",
    89: "סופה",
    90: "קרן",
    91: "כוח",
    92: "כוכב",
    93: "משב",
    94: "להבה",
    95: "רוח",
    96: "אגדה",
    97: "חזק",
    98: "שמש",
    99: "תהילה",
    100: "אלוף"
}
