from django.utils.translation import gettext_lazy as _

AVAILABLE_CITIES = [
    ('TLV', _('תל אביב יפו')),
    ('SKN', _('סכנין')),
]
SHOP_CATEGORIES=[
    ('grocery', _('מכולת')),
    ('shawarma', _('שווארמה')),
    ('falafel', _('פלאפל')),
    ('haircut', _('תספורת')),
    ('clothing', _('לבוש')),
    ('fast_food', _('אוכל מהיר')),
    ('cafes', _('בתי קפה')),
    ('bakeries', _('מאפיות')),
    ('desserts', _('קינוחים')),
    ('vegan', _('טבעוני')),
    ('sushi', _('סושי')),
    ('pizza', _('פיצה')),
    ('ice_cream', _('גלידות')),
    ('health_food', _('מזון בריאות')),
    ('meat_grill', _('בשרים וגריל')),
    ('asian', _('אסייתי')),
    ('italian', _('איטלקי')),
    ('drinks', _('שתייה')),
    ('CLOTHES', _('ביגוד')),
    ('TOYS', _('צעצועים')),
    ('ELECTRONICS', _('אלקטרוניקה')),
    ('BOOKS', _('ספרים')),
    ('OTHER', _('אחר')),
]


TEEN_COINS_EXPIRATION_MONTHS = 3 # the number of months after which a teen coin expires
MAX_REWARDS_PER_DAY = 1 # the maximum number of rewards per shop that the child can buy in one day
MAX_SHOPS_PER_DAY = 2  # max different shops from which a child can redeem per day
REDEMPTION_REQUEST_EXPIRATION_MINUTES = 60*4 # the number of minutes after which a redemption request expires
POINTS_PER_LEVEL = 100 # the number of points needed to reach the next level
MAX_PARENT_COINS = 130 # the maximum number of coins a parent can have when the monthly topup is granted
PARENT_TOPUP_AMOUNT = 50 # the amount of coins added to the parent's balance when the monthly topup is granted
CHILDREN_REQUIRE_DEFAULT_IMAGE = {"מחמד_חלילי","الطفل_إبراهيم"}  # the children who have special permissions to upload images in the check in/out page
SPECIAL_UPLOAD_PERMISSIONS_FOR_CHILDREN={"נור_גוראב","أحمد_دنف","آدم_تكروري"}  # the children who have special permissions to upload images in the check in/out page

CAMPAIGN_MENTOR_USERNAME = "אדם_תכרורי" # the username of the campaign mentor
CAMPAIGN_INSTITUTION_NAME = "المحمدية"   # the institution name of the campaign
CAMPAIGN_TIME_LIMIT_MINUTES = 1440 # the time limit for the campaign in minutes
CAMPAIGN_BAN_DURATION_HOURS = 1 # the duration of the campaign ban in hours

LEVELS = {
    1: _("מתחיל"),
    2: _("עוזר"),
    3: _("שואף"),
    4: _("שגריר"),
    5: _("מגן"),
    6: _("לוחם"),
    7: _("נועז"),
    8: _("אור"),
    9: _("חולם"),
    10: _("אלוף"),
    11: _("כוכב"),
    12: _("חזק"),
    13: _("נדיב"),
    14: _("רוח"),
    15: _("נסיך"),
    16: _("מאיר"),
    17: _("תותח"),
    18: _("מנהיג"),
    19: _("שולט"),
    20: _("אגדי"),
    21: _("שליט"),
    22: _("שר"),
    23: _("נאמן"),
    24: _("מוביל"),
    25: _("תורם"),
    26: _("אביר"),
    27: _("כוח"),
    28: _("זריז"),
    29: _("גדול"),
    30: _("עמיד"),
    31: _("חכם"),
    32: _("לבבי"),
    33: _("מהיר"),
    34: _("חסד"),
    35: _("ענק"),
    36: _("נחוש"),
    37: _("עוצמתי"),
    38: _("זוהר"),
    39: _("נסיך"),
    40: _("עליון"),
    41: _("שומר"),
    42: _("מקסים"),
    43: _("חולם"),
    44: _("משפיע"),
    45: _("שר"),
    46: _("איתן"),
    47: _("שליח"),
    48: _("מעורר"),
    49: _("מדהים"),
    50: _("פלאי"),
    51: _("מורה"),
    52: _("שר"),
    53: _("מאסטר"),
    54: _("עוזר"),
    55: _("תומך"),
    56: _("לב"),
    57: _("מתמיד"),
    58: _("אלוף"),
    59: _("שמש"),
    60: _("מאיר"),
    61: _("רעם"),
    62: _("חזון"),
    63: _("אש"),
    64: _("גל"),
    65: _("ברק"),
    66: _("חלוץ"),
    67: _("מושלם"),
    68: _("חבר"),
    69: _("ספיר"),
    70: _("נוצה"),
    71: _("מלאך"),
    72: _("שקט"),
    73: _("נס"),
    74: _("יוצר"),
    75: _("להב"),
    76: _("לב"),
    77: _("אחדות"),
    78: _("חמלה"),
    79: _("חלום"),
    80: _("תקווה"),
    81: _("אשד"),
    82: _("שלווה"),
    83: _("תדר"),
    84: _("שמחה"),
    85: _("פרץ"),
    86: _("פלא"),
    87: _("אלוף"),
    88: _("נסיך"),
    89: _("סופה"),
    90: _("קרן"),
    91: _("כוח"),
    92: _("כוכב"),
    93: _("משב"),
    94: _("להבה"),
    95: _("רוח"),
    96: _("אגדה"),
    97: _("חזק"),
    98: _("שמש"),
    99: _("תהילה"),
    100: _("אלוף")
}


TALLY_REDEMPTION_FORM_URL = "https://tally.so/r/mJQrA4"
