# Generated by Django 5.0.1 on 2025-04-07 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0004_child_last_level_awarded'),
        ('mentorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, help_text="e.g. '#FF5733' or 'blue' for UI themes", max_length=20)),
                ('points', models.PositiveIntegerField(default=0)),
                ('children', models.ManyToManyField(blank=True, related_name='mentor_groups', to='childApp.child')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='mentorApp.mentor')),
            ],
        ),
    ]
