# Generated by Django 5.0.1 on 2025-08-12 03:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorApp', '0002_mentorgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='allowed_proof_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('camera', 'העלאת תמונה מהמצלמה בלבד'), ('gallery', 'תמונה מהמצלמה או הגלריה'), ('auto_checkin', 'מאושר אוטומטית אחרי Check-in'), ('auto_checkout', 'מאושר אוטומטית אחרי Check-out'), ('none', 'ללא צורך בהעלאת תמונה  ')], max_length=20), blank=True, default=list, help_text='which proof options are allowed for this mentor', size=None),
        ),
    ]
