# Generated by Django 5.0.1 on 2024-12-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('identifier', models.CharField(max_length=5, unique=True, verbose_name='Identifier')),
                ('secret_code', models.CharField(max_length=3, verbose_name='Secret Code')),
            ],
        ),
    ]
