# Generated by Django 5.0.1 on 2025-02-27 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('childApp', '0001_initial'),
        ('institutionApp', '0001_initial'),
        ('mentorApp', '0001_initial'),
        ('parentApp', '0001_initial'),
        ('teenApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='completed_by_children', to='teenApp.task', verbose_name='Completed Tasks'),
        ),
        migrations.AddField(
            model_name='child',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='institutionApp.institution', verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='child',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='children', to='mentorApp.mentor', verbose_name='Mentors'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parentApp.parent', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='child',
            name='medals',
            field=models.ManyToManyField(blank=True, to='childApp.medal', verbose_name='Medals'),
        ),
    ]
