# Generated by Django 5.0.1 on 2025-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Medal Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
    ]
