# Generated by Django 5.0.1 on 2025-03-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0003_alter_child_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='last_level_awarded',
            field=models.IntegerField(default=1, verbose_name='Last Level Awarded'),
        ),
    ]
