# Generated by Django 5.0.1 on 2025-01-19 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0003_medal'),
        ('institutionApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='institutionApp.institution', verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_of', to=settings.AUTH_USER_MODEL, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='child',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='child',
            name='medals',
            field=models.ManyToManyField(blank=True, to='childApp.medal', verbose_name='Medals'),
        ),
    ]
