# Generated by Django 5.0.1 on 2025-01-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0004_child_institution_child_parent_alter_child_user_and_more'),
        ('parentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parentApp.parent', verbose_name='Parent'),
        ),
    ]
