# Generated by Django 5.0.1 on 2025-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0004_child_last_level_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='campaign_ban_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
