# Generated by Django 5.0.1 on 2025-05-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0005_child_campaign_ban_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakMilestoneAchieved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_day', models.PositiveIntegerField(help_text='Streak count at which this milestone was achieved.', verbose_name='Streak Day')),
                ('achieved_at', models.DateTimeField(auto_now_add=True, verbose_name='Achieved At')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_milestones', to='childApp.child', verbose_name='Child')),
            ],
            options={
                'verbose_name': 'Streak Milestone Achieved',
                'verbose_name_plural': 'Streak Milestones Achieved',
                'ordering': ['-achieved_at'],
                'unique_together': {('child', 'streak_day')},
            },
        ),
    ]
