# Generated by Django 5.0.1 on 2025-01-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0005_alter_child_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='criterion',
            field=models.CharField(default='default_criterion', max_length=255, verbose_name='Criterion Function'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medal',
            name='points_reward',
            field=models.IntegerField(default=0, verbose_name='Points Reward'),
        ),
    ]
