# Generated by Django 5.0.1 on 2025-01-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0005_alter_child_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
    ]
