# Generated by Django 5.0.1 on 2025-08-16 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0006_streakmilestoneachieved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('purchase', 'Shop purchases'), ('campaign', 'Campaign join/benefits'), ('all', 'All restricted actions')], default='purchase', max_length=24)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('note_child', models.CharField(blank=True, default='החשבון שלך כרגע חסום לביצוע רכישות', max_length=140)),
                ('note_staff', models.TextField(blank=True)),
                ('severity', models.CharField(default='hard', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_records', to='childApp.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_created', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['child', 'scope'], name='childApp_ch_child_i_a59a5d_idx'), models.Index(fields=['ends_at'], name='childApp_ch_ends_at_318770_idx')],
            },
        ),
    ]
