# Generated by Django 5.0.1 on 2025-01-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0006_child_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='city',
            field=models.CharField(blank=True, choices=[('TLV', 'תל אביב יפו'), ('TAM', 'טמרה')], max_length=3, null=True, verbose_name='City'),
        ),
    ]
