# Generated by Django 5.0.1 on 2025-09-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0007_childban'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_temp_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='trial_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
