# Generated by Django 5.0.1 on 2025-02-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0006_medal_criterion_medal_points_reward'),
        ('childApp', '0007_alter_child_city'),
    ]

    operations = [
    ]
