# Generated by Django 5.0.1 on 2025-02-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0008_merge_20250203_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Streak Date'),
        ),
        migrations.AddField(
            model_name='child',
            name='streak_count',
            field=models.IntegerField(default=0, verbose_name='Streak Count'),
        ),
    ]
