# Generated by Django 5.0.1 on 2025-09-29 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0008_child_is_temp_user_child_trial_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='childApp.child')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='childApp.child')),
            ],
            options={
                'verbose_name': 'Child Referral',
                'verbose_name_plural': 'Child Referrals',
            },
        ),
    ]
