# Generated by Django 5.0.1 on 2025-02-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0008_merge_20250203_1358'),
        ('childApp', '0008_merge_20250205_2201'),
        ('childApp', '0009_child_last_streak_date_child_streak_count'),
    ]

    operations = [
    ]
