# Generated by Django 5.0.1 on 2025-09-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0009_childreferral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childreferral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='childreferral',
            index=models.Index(fields=['referrer', 'created_at'], name='ref_by_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='childreferral',
            constraint=models.UniqueConstraint(fields=('referred_child',), name='unique_referral_per_child'),
        ),
    ]
