# Generated by Django 5.0.1 on 2025-10-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0010_alter_childreferral_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childreferral',
            name='reward_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childreferral',
            name='rewarded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='childreferral',
            name='trial_extended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
