# Generated by Django 5.0.1 on 2025-02-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0011_merge_20250222_2324'),
        ('childApp', '0011_merge_20250223_2307'),
        ('childApp', '0011_merge_20250225_1318'),
    ]

    operations = [
    ]
