# Generated by Django 5.0.1 on 2025-03-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='available_teencoins',
            field=models.IntegerField(default=0, verbose_name='Available TeenCoins'),
        ),
    ]
