# Generated by Django 5.0.1 on 2025-03-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentApp', '0002_parent_available_teencoins'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='last_monthly_topup',
            field=models.DateField(blank=True, help_text='Date of last monthly top-up', null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='available_teencoins',
            field=models.IntegerField(default=50, verbose_name='Available TeenCoins'),
        ),
    ]
