# Generated by Django 5.0.1 on 2025-04-01 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childApp', '0004_child_last_level_awarded'),
        ('parentApp', '0003_parent_last_monthly_topup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('plan', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit Card')], default='CASH', max_length=10)),
                ('auto_renew', models.BooleanField(default=False, help_text='If True, subscription will attempt to renew automatically.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='childApp.child', verbose_name='Child')),
            ],
            options={
                'verbose_name': 'Child Subscription',
                'verbose_name_plural': 'Child Subscriptions',
            },
        ),
    ]
