# Generated by Django 5.0.1 on 2025-02-27 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Institution Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('total_teencoins', models.IntegerField(default=0, verbose_name='Total Teencoins')),
                ('available_teencoins', models.IntegerField(default=0, verbose_name='Available Teencoins')),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution', to=settings.AUTH_USER_MODEL, verbose_name='Institution Manager')),
                ('mentors', models.ManyToManyField(blank=True, related_name='institutions', to='mentorApp.mentor', verbose_name='Mentors')),
            ],
        ),
        migrations.CreateModel(
            name='TeencoinsTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='institutionApp.institution')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='mentorApp.mentor')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='mentorApp.mentor')),
            ],
        ),
    ]
