# Generated by Django 5.0.1 on 2025-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Institution Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('mentors', models.ManyToManyField(related_name='institutions', to='mentorApp.mentor', verbose_name='Mentors')),
            ],
        ),
    ]
