# Generated by Django 5.0.1 on 2025-02-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutionApp', '0001_initial'),
        ('mentorApp', '0002_mentor_available_teencoins_alter_mentor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='available_teencoins',
            field=models.IntegerField(default=0, verbose_name='Available Teencoins'),
        ),
        migrations.AddField(
            model_name='institution',
            name='total_teencoins',
            field=models.IntegerField(default=0, verbose_name='Total Teencoins'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='institutions', to='mentorApp.mentor', verbose_name='Mentors'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Institution Name'),
        ),
    ]
