# Generated by Django 5.0.1 on 2025-02-12 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutionApp', '0003_institution_manager'),
        ('mentorApp', '0002_mentor_available_teencoins_alter_mentor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeencoinsTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='institutionApp.institution')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='mentorApp.mentor')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='mentorApp.mentor')),
            ],
        ),
    ]
