# Generated by Django 5.0.1 on 2025-03-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcategory',
            name='img',
            field=models.ImageField(blank=True, default='defaults/no-image.png', null=True, upload_to='media/images/donation_categories/', verbose_name='Image'),
        ),
    ]
