# Generated by Django 5.0.1 on 2025-03-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0002_donationcategory_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_spent', models.PositiveIntegerField()),
                ('date_spent', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.donationcategory')),
            ],
        ),
    ]
