# Generated by Django 5.0.1 on 2025-03-21 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0003_donationspending'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.PositiveIntegerField()),
                ('spending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.donationspending')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.donationtransaction')),
            ],
        ),
    ]
