# Generated by Django 5.0.1 on 2025-03-24 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0004_spendingallocation'),
        ('shopApp', '0004_redemption_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationspending',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.shop'),
        ),
    ]
