name: Django CI

on:
  push:
    branches:
      - main
      - tests/**
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: voludb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      DATABASE_NAME: voludb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      VOLUNTEEN_CI_NO_PHONE: true

      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        cd Volunteen
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run migrations
      working-directory: ./Volunteen
      run: |
        python manage.py migrate
      
    - name: Add 'phone' to auth_user (hacky workaround)
      working-directory: ./Volunteen
      run: |
        echo "ALTER TABLE auth_user ADD COLUMN phone VARCHAR(10);" | python manage.py dbshell
      

    - name: Run test childApp
      working-directory: ./Volunteen
      run: python manage.py test childApp.tests
        
    - name: Run test institutionApp
      working-directory: ./Volunteen
      run: python manage.py test institutionApp.tests
        
    - name: Run test managementApp
      working-directory: ./Volunteen
      run: python manage.py test managementApp.tests
        
    - name: Run test parentApp
      working-directory: ./Volunteen
      run: python manage.py test parentApp.tests
        
    - name: Run test mentorApp
      working-directory: ./Volunteen
      run: python manage.py test mentorApp.tests
        
    - name: Run test shopApp
      working-directory: ./Volunteen
      run: python manage.py test shopApp.tests
        