name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd Volunteen
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests for All Apps
      run: |
        cd Volunteen
        python manage.py test childApp.tests
        python manage.py test mentorApp.tests
        python manage.py test parentApp.tests
        python manage.py test institutionApp.tests
        python manage.py test managementApp.tests
        python manage.py test shopApp.tests
        python manage.py test teenApp.tests
