name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
        check-latest: true 

    - name: Install dependencies
      run: |
        cd Volunteen
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests for all apps
      run: |
        cd Volunteen
        python manage.py test childApp.tests
        python manage.py test mentorApp.tests
        python manage.py test parentApp.tests
        python manage.py test institutionApp.tests
        python manage.py test managementApp.tests
        python manage.py test shopApp.tests
        python manage.py test teenApp.tests
